modLoader="javafml"
loaderVersion="[${forge_version},)"
#issueTrackerURL = ""
license="Insert License Here"

[[mods]]
modId="bloodisfuel"
version="${version}"
displayName="Blood is Fuel"
authors="Me!"
description='''
This is an example description! Tell everyone what your mod is about!
'''
logoFile="icon.png"

[[dependencies.bloodisfuel]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.bloodisfuel]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version}"
ordering="NONE"
side="BOTH"

[[dependencies.bloodisfuel]]
modId="create"
mandatory=true
versionRange="[${create_forge_version},${create_forge_version_range})"
ordering="NONE"
side="BOTH"