import dev.ithundxr.silk.ChangelogText

plugins {
    id "idea"
    id "eclipse"
    id "maven-publish"
    id "dev.ithundxr.silk" version "0.11.15"
    id "me.modmuss50.mod-publish-plugin" version "0.8.3"
    id "net.neoforged.moddev.legacyforge" version "2.0.74"
    id "org.jetbrains.gradle.plugin.idea-ext" version "1.1.8" // https://github.com/JetBrains/gradle-idea-ext-plugin
}

apply from: "./gradle/java.gradle"
apply from: "gradle/property_loader.gradle"

boolean dev=System.getenv('RELEASE') == null || System.getenv('RELEASE').equals('false')
ext.buildNumber=System.getenv('BUILD_NUMBER')
String gitHash="${calculateGitHash() + (hasUnstaged() ? "-modified" : "")}"

base {
    archivesName="$mod_id-${minecraft_version}"
    group="${mod_group_id}"
    version=mod_version + (dev && buildNumber != null ? "-${buildNumber}" : '')
}

def refmap
mixin {
    refmap=add sourceSets.main, 'bloodisfuel.refmap.json'
    config 'bloodisfuel.mixins.json'
}

println "Java: ${System.getProperty 'java.version'}, " +
        "JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), " +
        "Arch: ${System.getProperty 'os.arch'}"

idea {
    module {
        downloadJavadoc=true
        downloadSources=true
    }
}


legacyForge {
    version="$minecraft_version-$forge_version"

    validateAccessTransformers=false

    if (file('src/main/resources/META-INF/accesstransformer.cfg').exists())
        accessTransformers.from "src/main/resources/META-INF/accesstransformer.cfg"

    parchment {
        minecraftVersion=minecraft_version
        mappingsVersion=parchment_version
    }

    mods {
        bloodisfuel {
            sourceSet sourceSets.main
        }
    }

    runs {
        // applies to all the run configs below
        configureEach {
            systemProperty 'forge.logging.markers', ''
            systemProperty 'forge.logging.console.level', 'info'
            jvmArguments=["-XX:+IgnoreUnrecognizedVMOptions", "-XX:+AllowEnhancedClassRedefinition"]
            //jvmArgs("-XX:-OmitStackTraceInFastThrow") // uncomment when you get exceptions with null messages etc
            //jvmArgs '-XX:+UnlockCommercialFeatures' // uncomment for profiling

            systemProperty 'mixin.debug.export', 'true'
            systemProperty 'mixin.debug.verbose', 'true'

            programArgument '-mixin.config=bloodisfuel.mixins.json'
        }

        client {
            client()

            gameDirectory=project.file('run')
        }

        server {
            server()

            gameDirectory=project.file('run/server')
        }

        data {
            data()

            gameDirectory=project.file('run')
            systemProperty 'forge.logging.markers', 'REGISTRIES,REGISTRYDUMP'
            systemProperty 'forge.logging.console.level', 'debug'
            programArguments.addAll("--mod", mod_id as String, "--all", "--output",
                    file("src/generated/resources/").getAbsolutePath(), "--existing",
                    file("src/main/resources").getAbsolutePath())
        }

        gameTestServer {
            type="gameTestServer"

            gameDirectory=project.file('run/gametest')
        }
    }
}

repositories {
    maven {url="https://maven.createmod.net"} // Create, Ponder, Flywheel
    maven {url="https://maven.tterrag.com"} // Registrate

    maven {url="https://maven.blamejared.com"} // JEI, Vazkii's Mods
    maven {url="https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"} // ForgeConfigAPIPort

    maven {url="https://www.cursemaven.com"}
    maven {url="https://api.modrinth.com/maven"}

//    maven {url='https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'}
//        content {includeGroupByRegex("software\\.bernie.*")
//        }
//    }

    mavenCentral()
    mavenLocal()
    flatDir {dir "libs"}
}

dependencies {
    // Create, Flywheel, Registrate, Create Diesel Generators
    modImplementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive=false }
    modImplementation("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}")
    modCompileOnly("dev.engine-room.flywheel:flywheel-forge-api-${minecraft_version}:${flywheel_version}")
    modRuntimeOnly("dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}")
    modImplementation("com.tterrag.registrate:Registrate:${registrate_version}")

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation("io.github.llamalad7:mixinextras-forge:0.4.1")

    modRuntimeOnly("curse.maven:create-diesel-generators-869316:6286179")
//    modImplementation("curse.maven:createaddition-439890:5658602")

    // JEI
    modCompileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    modCompileOnly("mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}")
    modImplementation("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")

    // Biomancy
//    modImplementation("maven.modrinth:biomancy:${biomancy_version}")
//    modImplementation("maven.modrinth:biofactory:${biofactory_version}")
//    modRuntimeOnly("software.bernie.geckolib:geckolib-forge-${minecraft_version}:${geckolib_version}")
//    implementation(group: "com.h2database", name: "h2-mvstore", version: "2.2.224")

    // Alex's Caves, Citadel
//    modImplementation("maven.modrinth:alexs-caves:2.0.2")
//    modRuntimeOnly("maven.modrinth:citadel:2.6.0")

    // TConstruct, Mantle
    //implementation fg.deobf("curse.maven:mantle-74924:6041712")
    //implementation fg.deobf("curse.maven:tinkers-construct-74072:6041763")

    if (!Boolean.getBoolean('idea.sync.active')) {
        annotationProcessor "org.spongepowered:mixin:0.8.5:processor"
    }
}

sourceSets.main {

    resources {
        srcDir 'src/generated/resources'
        exclude ".cache"
    }
}

processResources {
    def buildProps=project.properties.clone()

    // Replaces FML's magic file.jarVersion string with the correct version at build time.
    buildProps.put('file', [jarVersion: project.version])

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand buildProps as Map<String, ?>
    }
}

compileJava {
    options.compilerArgs=['-Xdiags:verbose']
}

jar {
    from('LICENSE') {
        rename { "${it}_${archivesBaseName}" }
    }

    manifest.attributes([
            "MixinConfigs": "bloodisfuel.mixins.json",
            "Git-Hash"    : gitHash
    ])
}

tasks.named("sourcesJar") {
    manifest.attributes([
            "Git-Hash": gitHash
    ])
}

final slimJar=tasks.register("slimJar", Jar) {
    archiveClassifier="slim"
    from(sourceSets.main.output)
    from(refmap)

    manifest.attributes([
            "MixinConfigs": "bloodisfuel.mixins.json",
            "Git-Hash"    : gitHash
    ])
}
obfuscation.reobfuscate(slimJar, sourceSets.main)

project.publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId base.archivesName.get()
            from components.java

            artifact(tasks.jar) {
                classifier="all"
            }
        }
    }

    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}
//modrinthToken=...
//curseforgeToken=...

def localProperties = new Properties()
def localPropertiesFile = rootProject.file("local.properties")
if (localPropertiesFile.exists()) {
    localPropertiesFile.withInputStream { stream -> localProperties.load(stream) }
}

publishMods {

    def curseforgeToken = localProperties.getProperty("curseforgeToken", "")
    def modrinthToken = localProperties.getProperty("modrinthToken", "")

    file=reobfJar.archiveFile
    dryRun=modrinthToken == null || curseforgeToken == null

    displayName="$mod_name $mod_version for mc$minecraft_version"
    version="$minecraft_version-$mod_version"
    changelog=ChangelogText.getChangelogText(project).toString()
    type=STABLE

    modLoaders.addAll("forge", "neoforge")

    curseforge {
        accessToken=curseforgeToken
        projectId="$curseforge_id"
        minecraftVersions.add(minecraft_version)
    }

    modrinth {
        accessToken=modrinthToken
        projectId="$modrinth_id"
        minecraftVersions.add(minecraft_version)
    }
}

String calculateGitHash() {
    try {
        def output=providers.exec {
            commandLine("git", "rev-parse", "HEAD")
        }
        return output.standardOutput.asText.get().trim()
    } catch (Throwable ignored) {
        return "unknown"
    }
}

boolean hasUnstaged() {
    try {
        def output=providers.exec {
            commandLine("git", "status", "--porcelain")
        }
        String result=output.standardOutput.asText.get().replace("/M gradlew(\\.bat)?/", "").trim()
        if (!result.isEmpty())
            println("Found stageable results:\n ${result}\n")
        return !result.isEmpty()
    } catch (Throwable ignored) {
        return false
    }
}