modLoader="javafml"
loaderVersion="[47,)"
license="${mod_license}"
issueTrackerURL="https://github.com/Electrisoma/bloodisfuel/issues/"

[[mods]]
modId="bloodisfuel"
version="${file.jarVersion}"
displayName="Create: Blood is Fuel!"
logoFile="logo.png"
authors="Electrisoma"
description='''
Create: Blood is Fuel! adds a new fuel type for Create: Diesel Generators that is (as the name says) blood.
'''

[[dependencies.bloodisfuel]]
modId="forge"
mandatory=true
versionRange="[47.1.3,)"
ordering="NONE"
side="BOTH"

[[dependencies.bloodisfuel]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.bloodisfuel]]
modId="create"
mandatory=true
versionRange="[6.0.1,6.1.0)"
ordering="NONE"
side="BOTH"