modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Electrisoma/bloodisfuel/issues/"

[[mods]]
modId="bloodisfuel"
version="1.1.5"
displayName="Create: Blood is Fuel!"
logoFile="logo.png"
authors="Electrisoma"
description='''
Create: Blood is Fuel! adds a new fuel type for machines.
'''

[[dependencies.bloodisfuel]]
modId="forge"
mandatory=true
versionRange="[47.1.3,)"
ordering="NONE"
side="BOTH"

[[dependencies.bloodisfuel]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.bloodisfuel]]
modId="create"
mandatory=true
versionRange="[6.0.1,6.1.0)"
ordering="NONE"
side="BOTH"