@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package net.electrisoma.bloodisfuel.config;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;