@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package net.electrisoma.bloodisfuel.registry.items.syringe_blade;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;