@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package net.electrisoma.bloodisfuel.registry.advancement;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;