@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package net.electrisoma.bloodisfuel.registry.particles;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;