@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package net.electrisoma.bloodisfuel.registry.fluid_utils;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;